### ISSUE TITLE
Add openjdk11 option to Java images

### ISSUE THREAD

**Issue by nealeu** [Shippable/buildami#623]
Open JDK 11 is the current supported release with 9 and 10 now out of support.  We therefore need to build against this version.

Could you lovely people add it to the next AMI?

**Comment by a-murphy** [comment]
OpenJDK 11 is available in the [v6.11.4 AMIs](http://docs.shippable.com/platform/runtime/machine-image/ami-v6114/#java).  Please open an issue in [Shippable/support](https://github.com/Shippable/support) if you have trouble configuring your build to use the new AMI.
